apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  labels:
    app: profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: simranarora264/profile-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: LOGGING_FILE_PATH
              value: /var/log/profile-service/profile-service.log
            - name: LOGSTASH_HOST
              value: "logstash"
            - name: LOGSTASH_PORT
              value: "5044"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/profile-service
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.14.1
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/profile-service
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: profile-service-log-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-service-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort