apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: simranarora264/product-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mydb
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: mypassword
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: LOGGING_FILE_PATH
              value: /var/log/product-service/product-service.log
            - name: LOGSTASH_HOST
              value: "logstash"
            - name: LOGSTASH_PORT
              value: "5044"
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/product-service
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.14.1
          volumeMounts:
            - name: log-volume
              mountPath: /var/log/product-service
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: product-service-log-pvc
        - name: filebeat-config
          configMap:
            name: filebeat-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-service-log-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort